apiVersion: v1
kind: Service

metadata:
  name: {{ .Release.Name }}-frontend-service
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: frontend
    app.kubernetes.io/instance: {{ .Release.Name }}

spec:
  selector:
    app.kubernetes.io/name: frontend
    app.kubernetes.io/instance: {{ .Release.Name }}    # ⬅️ ab deployment se match karega

  ports:
  - name: http
    port: 80
    targetPort: 80
    protocol: TCP

  type: ClusterIP