apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-mongodb-secret
  namespace: {{ .Release.Namespace }}
type: Opaque
stringData:
  username: {{ .Values.mongodb.username | quote }}
  password: {{ .Values.mongodb.password | quote }}