backend:
  replicaCount: 1
  image:
    repository: tanveeraws/saree-backend
    tag: v1

frontend:
  replicaCount: 1
  image:
    repository: tanveeraws/saree-frontend
    tag: v3

mongodb:
  image:
    repository: mongo
    tag: "7"
